version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js
      - npm install
      - echo Installing PM2
      - npm install -g pm2  # Install PM2 globally

  build:
    commands:
      - echo Build started on `date`
      - echo Starting the application with PM2
      - pm2 start app.js --name my-app || node app.js  # Start using PM2

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - app.js
    - package.json
    - package-lock.json
  discard-paths: no
