version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js
      - npm install

  build:
    commands:
      - echo Build started on `date`
      # Add any build commands here, e.g., npm run build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - app.js
    - package.json
    # Add any other files or directories needed for deployment
  discard-paths: no