version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js
      - npm install

  build:
    commands:
      - echo Build started on `date`
      # Removed `npm test` to avoid failure due to missing test script

  post_build:
    commands:
      - echo Build completed on `date`