version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js
      - npm install

  build:
    commands:
      - echo Build started on `date`
      # If you have a build script, uncomment the next line
      # - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Starting the application
      - pm2 start app.js --name my-app || node app.js  # Fallback if PM2 isn't available

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - app.js
    - package.json
    - package-lock.json  # Add this to ensure consistent installs
  discard-paths: no
